export const SEEDED_ISSUES = [
  {
    id: "1",
    title: "Severe Pothole near Waghawadi Road",
    category: "POTHOLE",
    severity: 5,
    status: "OPEN",
    latitude: 21.7600,
    longitude: 72.1400,
    address: "Waghawadi Road",
    ward: "Ward 4",
    department: "Roads & Infrastructure Department",
    reported_at: "2 hours ago",
    upvotes: 42,
    image_url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "2",
    title: "Large crater on Crescent Circle",
    category: "POTHOLE",
    severity: 4,
    status: "IN_PROGRESS",
    latitude: 21.7620,
    longitude: 72.1450,
    address: "Crescent Circle",
    ward: "Ward 3",
    department: "Roads & Infrastructure Department",
    reported_at: "5 hours ago",
    upvotes: 28,
    image_url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "3",
    title: "Multiple potholes near ST Bus Stand",
    category: "POTHOLE",
    severity: 3,
    status: "OPEN",
    latitude: 21.7640,
    longitude: 72.1480,
    address: "ST Bus Stand area",
    ward: "Ward 5",
    department: "Roads & Infrastructure Department",
    reported_at: "1 day ago",
    upvotes: 15,
    image_url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "4",
    title: "Deep pothole causing accidents",
    category: "POTHOLE",
    severity: 5,
    status: "OPEN",
    latitude: 21.7655,
    longitude: 72.1520,
    address: "Kalanala",
    ward: "Ward 6",
    department: "Roads & Infrastructure Department",
    reported_at: "2 days ago",
    upvotes: 65,
    image_url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "5",
    title: "Road surface eroded completely",
    category: "POTHOLE",
    severity: 4,
    status: "RESOLVED",
    latitude: 21.7580,
    longitude: 72.1380,
    address: "Jewel Circle",
    ward: "Ward 2",
    department: "Roads & Infrastructure Department",
    reported_at: "3 days ago",
    upvotes: 12,
    image_url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "6",
    title: "Potholes due to recent digging",
    category: "POTHOLE",
    severity: 3,
    status: "IN_PROGRESS",
    latitude: 21.7680,
    longitude: 72.1550,
    address: "Ghogha Circle",
    ward: "Ward 7",
    department: "Roads & Infrastructure Department",
    reported_at: "1 hour ago",
    upvotes: 5,
    image_url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "7",
    title: "Dangerous pothole near school",
    category: "POTHOLE",
    severity: 5,
    status: "OPEN",
    latitude: 21.7700,
    longitude: 72.1600,
    address: "Sardar Nagar",
    ward: "Ward 8",
    department: "Roads & Infrastructure Department",
    reported_at: "4 hours ago",
    upvotes: 38,
    image_url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "8",
    title: "Continuous potholes on service road",
    category: "POTHOLE",
    severity: 3,
    status: "RESOLVED",
    latitude: 21.7550,
    longitude: 72.1350,
    address: "Talaja Road",
    ward: "Ward 1",
    department: "Roads & Infrastructure Department",
    reported_at: "1 week ago",
    upvotes: 21,
    image_url: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "9",
    title: "Major Water Leak at Nilambag",
    category: "WATER_LEAK",
    severity: 4,
    status: "OPEN",
    latitude: 21.7650,
    longitude: 72.1450,
    address: "Nilambag Circle",
    ward: "Ward 5",
    department: "Water Supply & Sewerage Board",
    reported_at: "2 hours ago",
    upvotes: 56,
    image_url: "https://images.unsplash.com/photo-1604187351574-c75ca79f5807?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "10",
    title: "Drinking water pipe burst",
    category: "WATER_LEAK",
    severity: 5,
    status: "IN_PROGRESS",
    latitude: 21.7720,
    longitude: 72.1580,
    address: "Khodiyar Nagar",
    ward: "Ward 8",
    department: "Water Supply & Sewerage Board",
    reported_at: "12 hours ago",
    upvotes: 89,
    image_url: "https://images.unsplash.com/photo-1604187351574-c75ca79f5807?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "11",
    title: "Continuous leakage for 3 days",
    category: "WATER_LEAK",
    severity: 3,
    status: "OPEN",
    latitude: 21.7610,
    longitude: 72.1420,
    address: "Meghani Circle",
    ward: "Ward 4",
    department: "Water Supply & Sewerage Board",
    reported_at: "3 days ago",
    upvotes: 44,
    image_url: "https://images.unsplash.com/photo-1604187351574-c75ca79f5807?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "12",
    title: "Water wastage near public tap",
    category: "WATER_LEAK",
    severity: 2,
    status: "RESOLVED",
    latitude: 21.7660,
    longitude: 72.1500,
    address: "Bortalav",
    ward: "Ward 6",
    department: "Water Supply & Sewerage Board",
    reported_at: "4 days ago",
    upvotes: 15,
    image_url: "https://images.unsplash.com/photo-1604187351574-c75ca79f5807?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "13",
    title: "Underground pipe leaking",
    category: "WATER_LEAK",
    severity: 4,
    status: "OPEN",
    latitude: 21.7590,
    longitude: 72.1390,
    address: "Rupani Circle",
    ward: "Ward 2",
    department: "Water Supply & Sewerage Board",
    reported_at: "5 hours ago",
    upvotes: 31,
    image_url: "https://images.unsplash.com/photo-1604187351574-c75ca79f5807?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "14",
    title: "Broken Streetlight Night Bazaar",
    category: "STREETLIGHT",
    severity: 3,
    status: "RESOLVED",
    latitude: 21.7700,
    longitude: 72.1550,
    address: "Night Bazaar",
    ward: "Ward 7",
    department: "Electricity Department",
    reported_at: "1 week ago",
    upvotes: 18,
    image_url: "https://images.unsplash.com/photo-1516086884639-6d5dfbdf02bc?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "15",
    title: "Streetlights not working for a week",
    category: "STREETLIGHT",
    severity: 4,
    status: "OPEN",
    latitude: 21.7560,
    longitude: 72.1360,
    address: "Gaurishankar Lake road",
    ward: "Ward 1",
    department: "Electricity Department",
    reported_at: "1 week ago",
    upvotes: 52,
    image_url: "https://images.unsplash.com/photo-1516086884639-6d5dfbdf02bc?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "16",
    title: "Flickering lights causing distraction",
    category: "STREETLIGHT",
    severity: 2,
    status: "IN_PROGRESS",
    latitude: 21.7630,
    longitude: 72.1460,
    address: "Vidhyanagar",
    ward: "Ward 3",
    department: "Electricity Department",
    reported_at: "2 days ago",
    upvotes: 11,
    image_url: "https://images.unsplash.com/photo-1516086884639-6d5dfbdf02bc?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "17",
    title: "Dark patch on main highway",
    category: "STREETLIGHT",
    severity: 5,
    status: "OPEN",
    latitude: 21.7540,
    longitude: 72.1340,
    address: "Highway Approach",
    ward: "Ward 1",
    department: "Electricity Department",
    reported_at: "8 hours ago",
    upvotes: 74,
    image_url: "https://images.unsplash.com/photo-1516086884639-6d5dfbdf02bc?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "18",
    title: "Garbage overflow at Ghogha Circle",
    category: "GARBAGE",
    severity: 4,
    status: "OPEN",
    latitude: 21.7690,
    longitude: 72.1540,
    address: "Ghogha Circle",
    ward: "Ward 7",
    department: "Sanitation & Solid Waste Management",
    reported_at: "1 day ago",
    upvotes: 62,
    image_url: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "19",
    title: "Uncollected trash since 4 days",
    category: "GARBAGE",
    severity: 5,
    status: "IN_PROGRESS",
    latitude: 21.7710,
    longitude: 72.1610,
    address: "Sardar Nagar",
    ward: "Ward 8",
    department: "Sanitation & Solid Waste Management",
    reported_at: "4 days ago",
    upvotes: 91,
    image_url: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "20",
    title: "Dumpster overflowing onto road",
    category: "GARBAGE",
    severity: 3,
    status: "OPEN",
    latitude: 21.7645,
    longitude: 72.1490,
    address: "Haluriya Chowk",
    ward: "Ward 5",
    department: "Sanitation & Solid Waste Management",
    reported_at: "12 hours ago",
    upvotes: 27,
    image_url: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "21",
    title: "Illegal dumping of construction waste",
    category: "GARBAGE",
    severity: 4,
    status: "RESOLVED",
    latitude: 21.7570,
    longitude: 72.1370,
    address: "Subhashnagar",
    ward: "Ward 2",
    department: "Sanitation & Solid Waste Management",
    reported_at: "2 weeks ago",
    upvotes: 45,
    image_url: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "22",
    title: "Drainage blockage in Vadva",
    category: "DRAINAGE",
    severity: 4,
    status: "OPEN",
    latitude: 21.7670,
    longitude: 72.1530,
    address: "Vadva area",
    ward: "Ward 6",
    department: "Drainage & Sewerage Department",
    reported_at: "2 days ago",
    upvotes: 58,
    image_url: "https://images.unsplash.com/photo-1584824486509-112e4181f1ce?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "23",
    title: "Open manhole overflowing",
    category: "DRAINAGE",
    severity: 5,
    status: "OPEN",
    latitude: 21.7625,
    longitude: 72.1475,
    address: "Bhathiya area",
    ward: "Ward 4",
    department: "Drainage & Sewerage Department",
    reported_at: "6 hours ago",
    upvotes: 112,
    image_url: "https://images.unsplash.com/photo-1584824486509-112e4181f1ce?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "24",
    title: "Sewage water entering homes",
    category: "DRAINAGE",
    severity: 5,
    status: "IN_PROGRESS",
    latitude: 21.7685,
    longitude: 72.1560,
    address: "Kumbharwada",
    ward: "Ward 7",
    department: "Drainage & Sewerage Department",
    reported_at: "1 day ago",
    upvotes: 145,
    image_url: "https://images.unsplash.com/photo-1584824486509-112e4181f1ce?auto=format&fit=crop&q=80&w=400"
  },
  {
    id: "25",
    title: "Foul smell from blocked drain",
    category: "DRAINAGE",
    severity: 3,
    status: "RESOLVED",
    latitude: 21.7555,
    longitude: 72.1330,
    address: "Chitra GIDC",
    ward: "Ward 1",
    department: "Drainage & Sewerage Department",
    reported_at: "5 days ago",
    upvotes: 34,
    image_url: "https://images.unsplash.com/photo-1584824486509-112e4181f1ce?auto=format&fit=crop&q=80&w=400"
  }
];
